name: PrivateEncoderV2.0 Workflows 

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GitHubName }}
           git config --global user.email ${{ secrets.GitHubMail }}
           git config --global credential.helper store
           echo "https://Dark-super-me:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
           
       
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone -b main https://Dark-super-me:${{ secrets.GH_TOKEN }}@github.com/Dark-super-me/Dark.git
       - name: Running PrivateEncoderV2.0 Bot 
         timeout-minutes: 300
         continue-on-error: true
         run: |
           cd Dark
           docker build -t compressor . && docker run compressor
           
       - name: Loop workflow
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
           cd loop || exit 1
           echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
           git add looper.txt
           git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
           git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
